---
# tasks file for slave
      - name: Adding Kubeadm repo
        copy:
            src: kubernetes.repo
            dest: /etc/yum.repos.d
        
      - name: installing docker
        package:
                  name: "docker"
                  state: present
      
      - name: installing kubeadm
        package:
                    name: "kubeadm"
                    state: present

      - name: Enabling docker service      
        service: 
             name: docker
             state: started
             enabled: yes
      
      - name: Changing driver cgroup to systemd
        copy:
           src: daemon.json
           dest: /etc/docker/daemon.json

      - name: Restarting docker service
        service: 
               name: docker
               state: restarted

      - name: Removing swapfile from /etc/fstab
        mount:
                name: "{{ item }}"
                fstype: swap
                state: absent
        with_items:
                - swap
                - none
      
      - name: Enabling kubelet service
        service:
            name: kubelet
            daemon_reload: yes
            state: started
            enabled: yes

      - name: Installing iproute-tc
        package: 
           name: iproute-tc
           state: present        
           update_cache: yes
   
      - name: Copying k8s.conf file
        copy:
            src: k8s.conf
            dest: /etc/sysctl.d/k8s.conf

      - name: Enabling sysctl 
        shell: "sysctl --system"

      - name: Copying token file at /root location
        copy:
             src: /root/token.sh
             dest: /root/token.sh

      - name: Joining slave node to master node
        shell: "sh /root/token.sh" 
        register: joined

      - debug:
           msg: "{{ joined }}"

